name: Tests

on:
  push:
    branches:
      - 'main'
  pull_request: ~

env:
  COMPOSER_ROOT_VERSION: dev-master

jobs:
  tests:
    name: ${{ matrix.php }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php:
          - '8.1'
          - '8.2'

    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none

      - run: composer --version
      - run: composer validate --strict
      - run: composer global config --no-plugins allow-plugins.symfony/flex true
      - run: composer global require --no-scripts symfony/flex
      - run: composer update --prefer-dist
      - run: vendor/bin/phpunit --colors=always
